vich_uploader:
    db_driver: orm

    mappings:
        featured_images:
            uri_prefix: "%path.featured.images%"
            upload_destination: "%kernel.project_dir%/%path.public.featured.images%"
